import './components/sliders'
import './components/follow'
import './components/accordeon'
import './components/nav'
import './components/detailModal'
import './components/graph'
import './components/inputFile'
import './components/sort'
import './components/creator'

